[package]
name = "pennyworth"
version = "0.1.0"
authors = ["WilliamHammond <william.t.hammond@gmail.com>"]
edition = "2018"

[dependencies]
iced = "0.3"
chrono = "0.4"
log = "0.4"
simple_logger = "1.11.0"
